### ISSUE TITLE
Readme: write Homepage of linter tool; write package name for Ubuntu

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_lint_gometalint#6]
I cannot find package "gometa" nor "gometalint"
I cannot find homepage

cannot test.

**Comment by ahreenah** [comment]
I have written the link there:
https://github.com/alecthomas/gometalinter/releases

**Comment by Alexey-T** [comment]
надо написать в ридми, 
-или тул брать всегда оттуда то
-или указать нормальное имя пакета в убунту
