### ISSUE TITLE
Linux cant find linter tool

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_lint_gometalint#7]
устанеовил gometalinter в новую папку (Лин х64), добавил ее в PATH. и в .bashrc.
перезапуск ОС.

в PATH  папка есть.
ОС терминал пускает gometalinter.

но линтер не находит прогу
ERROR: gometalint cannot locate 'gometalinter'

скажи как запустить под Убунту.

**Comment by Alexey-T** [comment]
![Screenshot from 2020-03-24 20-11-31](https://user-images.githubusercontent.com/4154978/77456177-edb55100-6e0b-11ea-99a4-1dec6452ae9d.png)

**Comment by Alexey-T** [comment]
![Screenshot from 2020-03-24 20-14-56](https://user-images.githubusercontent.com/4154978/77456551-6fa57a00-6e0c-11ea-9168-4b6a0c59d14c.png)

**Comment by ahreenah** [comment]
попробуйте прописать полный путь в плаге)

**Comment by Alexey-T** [comment]
в самом плаге нельзя, юзер так делать не будет

**Comment by ahreenah** [comment]
fixed readme

**Comment by Alexey-T** [comment]
Ответь про это исью а не про ридми
